---
components:
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of my API
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
paths:
  "/api/appointments":
    get:
      summary: List all appointments
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
